name: go-lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Install golangci-lint
        run: |
          curl -sSfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.44.1
      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run
      - name: Upload lint to Codecov
        uses: codecov/codecov-action@v3